name = Bayitcham
description = A simple 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = bayitcham-layout

; Regions
regions[header]         = Header
regions[header2]        = Header2
regions[hp_slider]      = HP Slider
regions[hp_maincontent] = HP Main Content
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/bayitcham/bayitcham.layout.css
